defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
        users = ["admin:$apr1$NO5ChYGH$OqE9rpq2AGXVPtIeURAPW0"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]

  entryPoint = "traefik"
  dashboard = true #Enable dashboard
  debug = true #Enable debug

[acme]
email = "capobuf@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "dotroot.xyz"
watch = false
network = "prx"
exposedByDefault = false