version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: Wordpress
    depends_on:
      - database
    networks:
      - wordp
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html # Full wordpress project
    labels:
      - "traefik.backend=wordpress"
      - "traefik.docker.network=wordp"
      - "traefik.frontend.rule=Host:therealvoice.dotroot.xyz"
      - "traefik.enable=true"
      - "traefik.port=80"

  database:
    image: mariadb
    container_name: db_wordp
    networks:
      - wordp
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d

networks:
  wordp:
    external: false